baseurl = "https://hagbarth.github.io/"
languageCode = "en-us"
title = "Hagbarth"
theme = "hagbarth"

[taxonomies]
category = "categories"

[params]
Subtitle = "coder | entrepreneur | not really artist, but like art and music and stuff. And food!"
