baseurl = "https://hagbarth.github.io/"
languageCode = "en-us"
theme = "hagbarth"
title = "Hagbarth"
[params]
Subtitle = "coder | entrepreneur | not really artist, but like art and music and stuff. And food!"
[taxonomies]
category = "categories"
